### ISSUE TITLE
API service has no HTTP handler for / 

### ISSUE THREAD

**Issue by stefancocora** [UKHomeOffice/pttg-ip-api#18]
Please create an HTTP handler for `/` as currently ( in version=0.1.0-8.0d84b86 <= last bit is the git shasum ) the API springboot application doesn't have any HTTP handler.
If  `/` is not the correct URL path that the application should serve let me know.

These are the logs from the springboot api when querying the application:

querying through kubernetes port-forward - see https://trello.com/c/vIaQV19Z/16-setup-access-to-the-springboot-api

``` bash
curl localhost:58080 
{"status":{"code":"0008","message":"Resource not found: /"}}%  
```

**pttg-income-proving-api pod logs:**

``` bash
09:59:56.307 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
09:59:56.307 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
09:59:56.497 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 190 ms
09:59:56.700 [http-nio-8080-exec-1] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'dispatcherServlet'
09:59:56.799 [http-nio-8080-exec-1] DEBUG u.g.d.h.p.income.ApiExceptionHandler - No handler found for GET /
```

**Comment by atodd-hod** [comment]
There is nothing to serve at /.

I suppose we could serve the API documentation, which leads me to note that 1) the jar manifest isn't being created properly when the api-docs lib is generated, so I should fix that, and 2) The ServiceRunner has @EnableWebMvc which is disabling serving static content so need to remove that or work around it

**Comment by atodd-hod** [comment]
This is now complete in the tech-debt branch, which contains a number of other updates that need to be merged into master when convenient

**Comment by atodd-hod** [comment]
NB - you have to execute 'buildSpringBootWithApiDocs' instead of just 'build', which will generate a jar containing the api-docs with the appendix '-docs'
