### ISSUE TITLE
API service needs a /healthz handler to handle application healthchecking

### ISSUE THREAD

**Issue by stefancocora** [UKHomeOffice/pttg-ip-api#19]
This issue is about **application healthchecking**
Application healthcheck is not kubernetes specific, this type of healthchecking has existed before schedulers like kuber

In the kubernetes system the kubernetes "executor" that creates the containers inside the pod ( real name - **kubelet** ) can query for an HTTP endpoint to determine the health of the application being scheduled.
If the application's healthcheck doesn't respond with 200 Ok then the pod will be deleted and re-created automatically in an unattended fashion, without human intervention.

**λ**
Please create a `/healthz` endpoint that will act as the application healthcheck endpoint.
- the response when hitting `/healthz` should tell kubernetes if the application is healthy or not, how you implement this is really up to you.
-  the `/healthz` name is a kubernetes convention , if there are technical reasons why this can't be used then it can be changed
- kubernetes docs - http://kubernetes.io/docs/user-guide/liveness/

**Comment by atodd-hod** [comment]
This is now complete in the tech-debt branch, which contains a number of other updates that need to be merged into master when convenient

**Comment by atodd-hod** [comment]
This is complete in the tech-debt branch.

Healthcheck is exposed at /healthz

NB there is also /info for version info

These endpoints can be moved to a different port and/or host to restrict access if required, using these properties (which can be overridden with corresponding environment variables eg MANAGEMENT_PORT))

management.address=127.0.0.1
management.port=9081
